builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -extldflags "-static"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
dockers:
  - image_templates:
    - "ghcr.io/patrickdappollonio/docker-http-server:v{{ .RawVersion }}"
    - "ghcr.io/patrickdappollonio/docker-http-server:v{{ .Major }}"
    - "ghcr.io/patrickdappollonio/docker-http-server:latest"
    build_flag_templates:
    - "--label=org.opencontainers.image.title={{ .ProjectName }}"
    - "--label=org.opencontainers.image.description={{ .ProjectName }} version {{ .Version }}. See release notes at https://github.com/patrickdappollonio/{{ .ProjectName }}/releases/tag/v{{ .RawVersion }}"
    - "--label=org.opencontainers.image.url=https://github.com/patrickdappollonio/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.source=https://github.com/patrickdappollonio/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
