builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -extldflags "-static"
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
dockers:
  - image_templates:
    - "ghcr.io/patrickdappollonio/docker-http-server:{{ .Tag }}"
    - "ghcr.io/patrickdappollonio/docker-http-server:latest"
    extra_files:
    - 'html/'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
